version: '3.8'
services:
  petregistry:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DOG_API_KEY=${DOG_API_KEY}
      - SPRING_REDIS_HOST=redis
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
